learnable_mode: 3
log:
  exp_name: train
  overwrite_ok: False 
  exp_dir: results
  save_steps: 5000
  report_to: 'tensorboard'
data:
  train_data_dir: data/dtu/Rectified
  train_data_subsets: [scan3,scan4,scan5,scan6,scan9,scan10,scan11,scan12,scan13,scan14,scan15,scan16,scan17,scan18,scan19,scan20,scan22,scan23,scan24,scan28,scan32,scan33,scan35,scan36,scan37,scan42,scan43,scan44,scan46,scan47,scan48,scan49,scan50,scan52,scan53,scan59,scan60,    scan61,scan62,scan64,scan65,scan66,scan67,scan68,scan69,scan70,scan71,scan72,scan74,scan75,scan76,scan77,scan84,scan85,scan86,scan87,scan88,scan89,scan90,scan91,scan92,scan93,scan94,scan95,scan96,scan97,scan98,scan99,scan100,scan101,scan102,scan104,scan105,scan106,scan107,scan108,scan109,scan118,scan119,scan120,scan121,scan122,scan123,scan124,scan125,scan126,scan127,scan128]
  super_category_object_tokens: [object,object,object,object]
  placeholder_object_tokens: [<scan3>,<scan4>,<scan5>,<scan6>,<scan9>,<scan10>,<scan11>,<scan12>,<scan13>,<scan14>,<scan15>,<scan16>,<scan17>,<scan18>,<scan19>,<scan20>,<scan22>,<scan23>,<scan24>,<scan28>,<scan32>,<scan33>,<scan35>,<scan36>,<scan37>,<scan42>,<scan43>,<scan44>,<scan46>,<scan47>,<scan48>,<scan49>,<scan50>,<scan52>,<scan53>,<scan59>,<scan60>,<scan61>,<scan62>,<scan64>,<scan65>,<scan66>,<scan67>,<scan68>,<scan69>,<scan70>,<scan71>,<scan72>,<scan74>,<scan75>,<scan76>,<scan77>,<scan84>,<scan85>,<scan86>,<scan87>,<scan88>,<scan89>,<scan90>,<scan91>,<scan92>,<scan93>,<scan94>,<scan95>,<scan96>,<scan97>,<scan98>,<scan99>,<scan100>,<scan101>,<scan102>,<scan104>,<scan105>,<scan106>,<scan107>,<scan108>,<scan109>,<scan118>,<scan119>,<scan120>,<scan121>,<scan122>,<scan123>,<scan124>,<scan125>,<scan126>,<scan127>,<scan128>]
  placeholder_object_token: <object>
  fixed_object_token_or_path: object 
  super_category_object_token: object
  super_category_view_token: view
  dataloader_num_workers: 0
  camera_representation: "dtu-12d"
  dtu_subset: 0
  dtu_lighting: 3
  augmentation_key: 5
model:
  pretrained_model_name_or_path: stabilityai/stable-diffusion-2-1
  use_nested_dropout: False
  nested_dropout_prob: 0.5
  arch_mlp_hidden_dims: 64
  normalize_object_mapper_output: True
  normalize_view_mapper_output: True
  use_positional_encoding_object: True
  use_positional_encoding_view: True
  pe_sigmas: {'sigma_t': 0.03, 'sigma_l': 2.0, 'sigma_phi': 2.0, 'sigma_theta' : 2.0  }
  num_pe_time_anchors: 10
  output_bypass_object: True
  output_bypass_view: True
  word_embedding_dim: 1024
  arch_view_disable_tl: False
  arch_view_net: 15
  arch_view_mix_streams: 0
  pe_sigma_exp_key: 2
  output_bypass_alpha_view: 5
  output_bypass_alpha_object: 5
eval:
  validation_steps: 5000
  num_denoising_steps: 30
  validation_seeds: [0, 1]
  num_validation_images: 2
  eval_placeholder_object_tokens: [<scan97>,<scan33>, <scan65>, <scan20>, <scan106>, <scan32>]
optim:
  max_train_steps: 50000
  learning_rate: 1e-3
  train_batch_size: 3
  gradient_accumulation_steps: 3
