learnable_mode: 3
log:
  exp_name: train
  overwrite_ok: False 
  exp_dir: results
  save_steps: 5000
  report_to: 'tensorboard'
data:
  train_data_dir: data/dtu/Rectified
  train_data_subsets: [scan65,scan125,scan7,scan105]
  super_category_object_tokens: [object,object,object,object]
  placeholder_object_tokens: [<skull>,<statue>,<statue2>,<toy>]
  placeholder_object_token: <object>
  fixed_object_token_or_path: object 
  super_category_object_token: object
  super_category_view_token: view
  dataloader_num_workers: 0
  camera_representation: "dtu-12d"
  dtu_subset: 0
  dtu_lighting: 3
  augmentation_key: 7
model:
  pretrained_model_name_or_path: stabilityai/stable-diffusion-2-1
  use_nested_dropout: False
  nested_dropout_prob: 0.5
  arch_mlp_hidden_dims: 64
  normalize_object_mapper_output: True
  normalize_view_mapper_output: True
  use_positional_encoding_object: True
  use_positional_encoding_view: True
  pe_sigmas: {'sigma_t': 0.03, 'sigma_l': 2.0, 'sigma_phi': 2.0, 'sigma_theta' : 2.0  }
  num_pe_time_anchors: 10
  output_bypass_object: True
  output_bypass_view: True
  word_embedding_dim: 1024
  arch_view_disable_tl: False
  arch_view_net: 15
  arch_view_mix_streams: 0
  pe_sigma_exp_key: 2
  output_bypass_alpha_view: 5
  output_bypass_alpha_object: 5
eval:
  validation_steps: 5000
  num_denoising_steps: 30
  validation_seeds: [0, 1]
  num_validation_images: 2
  eval_placeholder_object_tokens:  [<skull>, <statue>, <toy>]
optim:
  max_train_steps: 10000
  learning_rate: 1e-3
  train_batch_size: 3
  gradient_accumulation_steps: 3
